### ISSUE TITLE
Avatar seems to have stopped working.

### ISSUE THREAD

**Issue by lettie16** [khalwat/disqus#3]
Hi

Firstly great plugin.

It seems that the avatar has stopped being sent over to disqus. Still logs in ok but the avatars have now reverted to the disqus noavatar default. They were working initially. IS it possible Disqus have changed something to cause this?

Cheers

**Comment by khalwat** [comment]
I'm not sure, I'll set up a test environment to see.  Can you point me to a URL where this is happening?

**Comment by lettie16** [comment]
Thanks khalwat. I can't point you to a url unfortunately as it's behind a login so hopefully you can find out what is happening without it.

**Comment by khalwat** [comment]
Okay, it should be all fixed in the latest version, go ahead and `git pull` it.
