### ISSUE TITLE
Custom Login/Logout Links - Instructions Missing

### ISSUE THREAD

**Issue by ProofofNatalie** [khalwat/disqus#4]
I'm creating custom login/logout links for my integration, and I noticed you have a link on the master description of this plugin, but the link is broken where it says "Adding your own SSO login and logout links"

I've been able to create a custom login box just fine, but I'm having a hard time getting a custom login controller setup in the plugin, and was wondering if this is something that's already included or should I be creating my own?

**Comment by khalwat** [comment]
Weird that the link isn't right, sorry about that, I'll fix it.  The link is this:

https://help.disqus.com/customer/portal/articles/236206-integrating-single-sign-on#sso-login

You only need this is you want to have a custom login button displayed in the Disqus UI itself.  If you have some other method that people typically use to log into your self, you don't need it.  They'll already be logged in, and the SSO takes care of auth'ing them.

**Comment by ProofofNatalie** [comment]
Thanks so much. For anyone else who's interested, I created a custom controller to create a logout button that automatically redirects to the same page (by default I have the logout going back to the homepage). 

To do so, I created a controllers folder within the plugin and uploaded the attached Disqus_SsoController file (but made it .php instead of .txt). Then I named the logout link in the plugin's settings to point to this action... which for me was http://example.com/actions/disqus/sso/logoutRedirect

[Disqus_SsoController.txt](https://github.com/khalwat/disqus/files/41958/Disqus_SsoController.txt)

**Comment by khalwat** [comment]
Great!  I'm not even sure you had to create a controller for this... you just need to give it a URL to a page where people can log into your site.  Ditto for logging out.

**Comment by ProofofNatalie** [comment]
The login part was easy, but the logout is a bit different. There actually isn't a template or page where people go to logout, it's a built-in Craft controller, so I needed to kind of duplicate it with a different redirect because of my default site settings (which redirects them to the homepage and not back to the same page). Thanks so much for the plugin, btw! I had attempted to do it all on my own and then found your plugin, which saved me tons of time :)

**Comment by khalwat** [comment]
Ah I understand, makes sense.  One suggestion would be to put this controller into your own plugin, rather than piggybacking on the Vanillaforums plugin, because any updates (like the one I just issued) will wipe it out.

What you ended up doing looks generic enough that I can probably just add it to the plugin, though.

**Comment by khalwat** [comment]
Okay, check out the latest repo, I built the logout URL controller into it.  Note that the URL is slightly different than yours: `http://example.com/actions/disqus/logoutRedirect`

This way you can keep up to date with any changes/additions to the plugin without it breaking your logout URL addition.

**Comment by ProofofNatalie** [comment]
Awesome! That's a huge help. Thank you :)
