### ISSUE TITLE
Disqus JS compatability with Cloudflare Rocketloader

### ISSUE THREAD

**Issue by webzes** [khalwat/disqus#6]
Hello

I would like to make a feature request to change the javascript tag to:

`<script data-cfasync="false" type="text/javascript">`

Disqus comments do not work when the Cloudflare Rocket Loader feature is enabled. Adding `data-cfasync="false"` disables Rocket Loader for specific tags.

This could be a simple plugin setting to turn on/off this feature or the default tag could be modified with it in.

I found this solution from [https://mikecoutermarsh.com/cloudflares-rocket-loader-disqus/](https://mikecoutermarsh.com/cloudflares-rocket-loader-disqus/) when investigating the problem on my site.

More information can be found here: [https://support.cloudflare.com/hc/en-us/articles/200168056-What-does-Rocket-Loader-do-](https://support.cloudflare.com/hc/en-us/articles/200168056-What-does-Rocket-Loader-do-)

**Comment by khalwat** [comment]
This is addressed in 1.0.2:

https://github.com/nystudio107/disqus
